The-Strategy-Unit/nhp_model

.github/workflows/build_container.yaml

* pull the latest version of the container down, will slightly improve performance
* ensure the storage account env var is only set on what we push to azure cr

update deploy containers

---

model/data/databricks.py
notebooks/national_run.py

Closes #316 
Note: 
- Removes imd_quintile and sushrg_trimmed from OP data for memory reasons
- Limits PBM to principal projection only

Updates PBM notebook and data.databricks.DatabricksNational

---

notebooks/generate_synthetic_datasets.ipynb

fix missing comma in generate synthetic data notebook

---

model/inpatients.py
model/results.py
queue/sample_params.json
tests/test_inpatient_efficiencies.py
tests/test_inpatients.py
tests/test_results.py

Implement SDEC mitigators

---

model/model_iteration.py
tests/test_model_iteration.py

ensures that the step counts are added into A&E, rather than just removed from inpatients
fixes #332

fixes sdec step counts

---

.github/workflows/deploy_dev.yaml

fix typo in deploy_dev yaml

---

.github/workflows/deploy_schema.yaml

rename ids in deploy_schema.yaml

---

.github/workflows/deploy_schema.yaml

update versions of actions in deploy_schema.yaml

---

.github/workflows/deploy_schema.yaml

amend deploy schema workflow, merging version steps

---

model/data/databricks.py

data has switched from being stored in parquet files to unity catalog

updates PBM data to use the new population projections data

---

readme.md

update readme with json schema info

---

model/data/databricks.py

This is a temporary measure - inequalities not currently working in PBM - need to figure out a longer term solution (https://github.com/The-Strategy-Unit/nhp_model/issues/353)

Bugfix to allow PBM to run

---

pyproject.toml

suggestion is that fastparquet is no longer being actively maintained, so switching to pyarrow

switch from fastparquet to pyarrow

---

tests/data/test_data.py
tests/data/test_local.py
tests/data/test_reference.py
tests/test_docker_run.py
tests/test_health_status_adjustment.py
tests/test_helpers.py
tests/test_hsa_gams.py
tests/test_inpatient_efficiencies.py
tests/test_inpatients.py
tests/test_model.py
tests/test_model_iteration.py
tests/test_outpatients.py
tests/test_results.py
tests/test_run_model.py

`tests/data` is now fixed. Didn't realise it was just a handful of tests :facepalm: 
Edit: CodeCov fails as expected, because
```console
tests/test_docker_run.py .......................
Error: Process completed with exit code 1.
```

386 fix tests data

---

notebooks/national_run.py

fixes #389 by adding some notes to the top of the notebook on what to do to get this to work

update national model to use nhp-model wheel

---

.github/workflows/build_app.yaml
.gitignore
Dockerfile
pyproject.toml
uv.lock

- **adds dynamic versioning**
- **adds new build action to create wheels**
separately developed this action in a throw away (private) repo, and have got it working there

create .whl of the app

---

readme.md

improve readme with developer info and link to one page explainer

---

notebooks/national_run.py
src/nhp/model/data/databricks.py

adds an argument to select the projection_year for demographics

---

src/nhp/model/data/databricks.py

closes #349 - switches to using the extracted parquet files for demographics/births

uses the extracted tables for the demographic/birth data for national run

---

src/nhp/__init__.py
src/nhp/docker/__init__.py
src/nhp/docker/__main__.py
src/nhp/docker/config.py
src/nhp/docker/run.py
src/nhp/model/__init__.py
src/nhp/model/__main__.py
src/nhp/model/aae.py
src/nhp/model/activity_resampling.py
src/nhp/model/data/__init__.py
src/nhp/model/data/data.py
src/nhp/model/data/databricks.py
src/nhp/model/data/local.py
src/nhp/model/data/reference/__init__.py
src/nhp/model/health_status_adjustment.py
src/nhp/model/helpers.py
src/nhp/model/inpatients.py
src/nhp/model/model.py
src/nhp/model/model_iteration.py
src/nhp/model/outpatients.py
src/nhp/model/results.py
src/nhp/model/run.py
tests/nhp/model/test__main__.py
tests/nhp/model/test_health_status_adjustment.py

runs `ruff check --fix --unsafe-fixes src` and cleans up lint issues

fix lint issues

---

readme.md

Updated the image URL

---

pyproject.toml

previously needed, but long since removed from the code.

removes unused package depedencies from pyproject.toml

---

src/nhp/model/activity_resampling.py
src/nhp/model/model.py
src/nhp/model/model_iteration.py
tests/unit/nhp/model/test_activity_resampling.py
tests/unit/nhp/model/test_model.py
tests/unit/nhp/model/test_model_iteration.py

Remove covid adjustment

---

pyproject.toml

- **remove pyright section**
- **adds some indentation to list**

clean up pyproject toml

---

notebooks/generate_synthetic_datasets.ipynb
params-schema.json
queue/params-sample.json
src/nhp/model/activity_resampling.py
src/nhp/model/data/data.py
src/nhp/model/data/databricks.py
src/nhp/model/data/local.py
src/nhp/model/model.py
tests/unit/nhp/model/data/test_data.py
tests/unit/nhp/model/data/test_local.py
tests/unit/nhp/model/test_activity_resampling.py
tests/unit/nhp/model/test_model.py

Closes #467 
Note #490 - current implementation only works for provider level model runs

Update inequalities functionality
